org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8
org.gradle.parallel=true
systemProp.file.encoding=UTF-8
systemProp.user.home=D\:/gradle_user_home
systemProp.android.user.home=D\:/android_home
android.useAndroidX=true
android.enableJetifier=true
kotlin.experimental.tryK2=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
